version: "3"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=ggPwd!
      - POSTGRES_USER=gg
      - POSTGRES_DB=gg
    volumes:
      - ./docker/db:/var/lib/pgsql/data
    ports:
      - "1466:5432"

