version: "3"

volumes:
  backend_sock:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - backend_sock:/var/run/backend

  backend:
    image: gg/backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - MEDIA_DIRECTORY
      - TOKEN_HOUR_LIFESPAN
      - API_SECRET
    volumes:
      - backend_sock:/var/run

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data

