services:
  nginx:
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "8085:80"

  backend:
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=bookeper
      - DB_PASSWORD=bookeper
      - DB_DATABASE=bookeper
      - MEDIA_DIRECTORY="../media"
      - TOKEN_HOUR_LIFESPAN=12
      - API_SECRET=changeme

  db:
    environment:
      - POSTGRES_PASSWORD=bookeper
      - POSTGRES_USER=bookeper
      - POSTGRES_DB=bookeper
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
