volumes:
  backend_sock:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend/dist:/var/www/frontend
      - ./media:/media
      - backend_sock:/var/run/backend

  backend:
    image: bookeeper/backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - MEDIA_DIRECTORY=/media
      - TOKEN_HOUR_LIFESPAN
      - API_SECRET
    volumes:
      - backend_sock:/var/run
      - ./media:/media

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data

  generate_back_api:
    image: swag/autodoc
    build:
      context: ./docker/autodoc

  migration_tool:
    image: gomigtools/atlas
    build:
      context: ./docker/migtools