version: "3"

services:
  backend:
    image: gg/backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    restart: unless-stopped
    environment:
      - WEBAPP_HOST=backend
      - WEBAPP_PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=gg
      - DB_PASSWORD=ggPwd!
      - DB_DATABASE=gg
    ports:
      - "8081:80"

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=ggPwd!
      - POSTGRES_USER=gg
      - POSTGRES_DB=gg
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    ports:
      - "1466:5432"
