version: "3"

services:
  backend:
    image: gg/backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    restart: unless-stopped
    environment:
      - WEBAPP_HOST
      - WEBAPP_PORT
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - MEDIA_DIRECTORY
    ports:
      - "8081:80"

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    ports:
      - "1466:5432"
