// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package book

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Wire(db *gorm.DB) *BookControllerAPI {
	bookRepositoryImpl := ProvideBookRepository(db)
	bookServiceImpl := ProvideBookService(bookRepositoryImpl)
	bookControllerAPI := ProvideBookController(bookServiceImpl)
	return bookControllerAPI
}
